📁 audio/
📁 fonts/
  📄 ARCADE.TTF
  📄 OpenDyslexic-Bold.otf
  📄 OpenDyslexic-BoldItalic.otf
  📄 OpenDyslexic-Italic.otf
  📄 OpenDyslexic-Regular.otf
  📄 OpenDyslexicAlta-Bold.otf
  📄 OpenDyslexicAlta-BoldItalic.otf
  📄 OpenDyslexicAlta-Italic.otf
  📄 OpenDyslexicAlta-Regular.otf
  📄 OpenDyslexicMono-Regular.otf
  📄 SHOWG.TTF
📁 images/
  📁 defaults/
    📄 default_answer.png
    📄 default_player.png
    📄 default_popup.png
    📄 default_question_bg.png
    📄 default_reaction.png
    📄 default_shield.png
    📄 default_slot.png
    📄 default_strip_answer.png
    📄 default_strip_slot.png
    📄 default_strip_trivia.png
    📄 default_wrong_mask.png
  📁 popup_cards/
    📄 popup_ffw.png
    📄 popup_ffw_02.png
    📄 popup_ffw_03.png
    📄 popup_ffw_04.png
    📄 popup_overshoot_04.png
    📄 popup_rew_01.png
    📄 popup_rew_02.png
    📄 popup_rew_03.png
  📁 question_cards/
    📁 aficionados/
      📄 answer_01.png
      📄 question_bg.png
      📄 strip_answer.png
      📄 strip_trivia.png
    📁 coaches/
      📄 answer_01.png
      📄 question_bg.png
      📄 strip_answer.png
      📄 strip_trivia.png
    📁 leagues/
      📄 answer_01.png
      📄 question_bg.png
      📄 strip_answer.png
      📄 strip_trivia.png
    📁 players/
      📄 answer_01.png
      📄 question_bg.png
      📄 strip_answer.png
      📄 strip_trivia.png
    📁 soccer_rules/
      📄 answer_01.png
      📄 question_bg.png
      📄 strip_answer.png
      📄 strip_trivia.png
    📁 world_cup/
      📄 answer_01.png
      📄 question_bg.png
      📄 strip_answer.png
      📄 strip_trivia.png
  📁 reaction_cards/
    📄 wrong_corner_01.png
    📄 wrong_kick_01.png
    📄 wrong_penalty_01.png
    📄 wrong_red_01.png
    📄 wrong_yellow_01.png
  📁 slot_cards/
    📄 slot_corner_01.png
    📄 slot_kick_01.png
    📄 slot_penalty_01.png
    📄 slot_red_01.png
    📄 slot_yellow_01.png
  📁 teams_cards/
    📁 leon/
      📄 player_01.png
      📄 shield.png
    📁 pachuca/
      📄 player_01.png
      📄 shield.png
  📁 _system/
    📄 Basic_Dialogue_Box.png
    📄 Basic_Dialogue_Box_Thick.png
    📄 board_bg.png
    📄 player_chip_blue.png
    📄 player_chip_pink.png
    📄 SoccerBall_Icon.png
