enum GameState {
	IDLE = 0,
	AWAITING_ROLL = 1,
	ROLLING = 2,                 # 🔹 Added here
	MOVING_CHIP = 3,
	RESOLVING_SLOT = 4,
	QUIZ_ACTIVE = 5,
	FEEDBACK_SHOWN = 6,
	END_TURN = 7,
	SHOWING_QUIZ = 8,
	WAITING_AFTER_QUIZ = 9,
	SHOWING_HALFTIME = 10,
	WAITING_AFTER_HALFTIME = 11,
	SHOWING_WINNER = 12,
	WAITING_AFTER_WINNER = 13,
	START_MENU = 99
}
